//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektBazyDanych
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.DiseaseHistories = new HashSet<DiseaseHistory>();
        }
    
        public int id { get; set; }
        public int age { get; set; }
        public string sex { get; set; }
        public string origin { get; set; }
        public System.DateTime inZooSince { get; set; }
        public string name { get; set; }
        public string spiece { get; set; }
        public int runwayID { get; set; }
    
        public virtual Runway Runway { get; set; }
        public virtual Spiece Spiece1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiseaseHistory> DiseaseHistories { get; set; }
    }
}
