//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektBazyDanych
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Runway
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Runway()
        {
            this.Animals = new HashSet<Animal>();
            this.Supervisors = new HashSet<Supervisor>();
        }
        [Display(Name = "Id wybiegu")]
        public int id { get; set; }
        [Display(Name = "Nazwa wybiegu")]
        [Required(ErrorMessage = "Wpisz nazwę")]
        public string name { get; set; }
        [Display(Name = "Powierzchnia w m²")]
        [Required(ErrorMessage = "Wpisz powierzchnię")]
        [RegularExpression("[0-9]*", ErrorMessage = "Proszę podać liczbę dodatnią")]
        public double area { get; set; }
        [Display(Name = "Ilość zwierząt")]
        public int animalCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supervisor> Supervisors { get; set; }
    }
}
