//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektBazyDanych
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ServicePoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServicePoint()
        {
            this.ServicePointWorkers = new HashSet<ServicePointWorker>();
        }
        [Display(Name = "Id punktu")]
        public int id { get; set; }
        [Display(Name = "Nazwa punktu")]
        [Required(ErrorMessage = "Wpisz nazwê")]
        public string name { get; set; }
        [Display(Name = "Iloœæ pracowników")]
        [Required(ErrorMessage = "Pole wymagane")]
        public int howManyWorkers { get; set; }
        [Display(Name = "Przychód w z³")]
        [Required(ErrorMessage = "Pole wymagane")]
        public double income { get; set; }
        [Display(Name = "Typ")]
        [Required(ErrorMessage = "Wpisz typ")]
        public string type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePointWorker> ServicePointWorkers { get; set; }
    }
}
