//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektBazyDanych
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Settlement
    {
        [Display(Name = "Id rozliczenia")]
        public int shipmentId { get; set; }
        [Display(Name = "Data utworzenia")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime creationDate { get; set; }
        [Display(Name = "Data modyfikacji")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime modificationDate { get; set; }
        [Display(Name = "Rok")]
        public int year { get; set; }
        [Display(Name = "Miesi¹c")]
        public int month { get; set; }
        [Display(Name = "Suma")]
        public int sum { get; set; }
        [Display(Name = "Zatwierdzone")]
        public bool approved { get; set; }

        public virtual Shipment Shipment { get; set; }
        public virtual Shipment Shipment1 { get; set; }
    }
}
