//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektBazyDanych
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Spiece
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Spiece()
        {
            this.Animals = new HashSet<Animal>();
            this.Foods = new HashSet<Food>();
        }
        [Display(Name = "Id gatunku")]
        public int id { get; set; }
        [Display(Name = "Nazwa gatunku")]
        [Required(ErrorMessage = "Wpisz nazwê")]
        [RegularExpression("[^0-9]*", ErrorMessage = "Nazwa gatunku nie mo¿e zawieraæ cyfr")]
        public string name { get; set; }
        [Display(Name = "Iloœæ zjadanego po¿ywienia w kg")]
        public int appetite { get; set; }
        [Display(Name = "Iloœæ")]
        public int howMany { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Food> Foods { get; set; }
    }
}
