//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektBazyDanych
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [Display(Name = "Login")]
        public string login { get; set; }
        [Display(Name = "Has³o zaszyfrowane")]
        public string passwordHash { get; set; }
        [Display(Name = "Has³o")]
        [DataType(DataType.Password)]
        public string passwordSalt { get; set; }
        [Display(Name = "Email")]
        public string email { get; set; }
        [Display(Name = "Imiê")]
        [Required(ErrorMessage = "Wpisz imiê")]
        [RegularExpression("[^0-9]*", ErrorMessage = "Imiê nie mo¿e zawieraæ cyfr")]
        public string firstName { get; set; }
        [Display(Name = "Nazwisko")]
        [Required(ErrorMessage = "Wpisz nazwisko")]
        [RegularExpression("[^0-9]*", ErrorMessage = "Nazwisko nie mo¿e zawieraæ cyfr")]
        public string lastName { get; set; }
    }
}
